### ISSUE TITLE
Inactive connection

### ISSUE THREAD

**Issue by Mte90** [progga/footle#1]
I am trying to use that tools but I get only:
```
2018/08/28 10:13:02 Inactive connection.
2018/08/28 10:13:13 Inactive connection.
2018/08/28 10:14:41 Inactive connection.
```
From inside a VM, I add the breakpoint for the UI and when I refresh the page I get that output.

Maybe the UI or the cli can add a label that say that xdebug is running and available.

Also I was using the sessionkey with other tools and the connection was working.

**Comment by progga** [comment]
On Tue, Aug 28, 2018 at 10:18:35AM +0000, Daniele Scasciafratte wrote:

> I am trying to use that tools but I get only:
> ```
> 2018/08/28 10:13:02 Inactive connection.
 
Hi Daniele, thanks for being the first person to try out Footle :)  That "Inacive connection" message happens when Footle tries to send debugging commands to Xdebug even though Xdebug has not established a connection with Xdebug.  You can get into this situation by clicking any of the control buttons (except "Off") outside of a debugging session.  I really need to disable the control buttons in this state.  But as you can see, I haven't done it yet.  The UI needs tons of improvement.

> Maybe the UI or the cli can add a label that say that xdebug is running and available.

At the moment, there is a tiny bit of hint available.  You will notice a thick *red* bar among the control buttons.  This bar will change its *colour* based on what's happening.  Here is a quick explanation of the colours:
- Red: Waiting for a call from Xdebug.
- Amber: Xdebug has called.  Waiting for user interaction.  This is when the control buttons (e.g. "In") are useful.
- Green: Programme execution is happening.  Expecting Xdebug to come back.
- Gray: Footle is sleeping.  It will *not* take a call from Xdebug.  You see it when you click the "Off" button.

Again, these are entirely undocumenated.  I want to create some more documenation once Footle becomes a little more reliable.  Sorry for the pain in the mean time :(

In the worse case, if you feel that Xdebug is never talking to Footle, then launch Footle with the "--vvv" option.  This will dump the raw XML traffic from Xdebug.  If Xdebug never calls in, you will never see any XML.

**Comment by Mte90** [comment]
Hi, no worry I saw that is an experimental phase :-)
I executed with `-vvv` with no output a part what I written.
I will wait how evolve this project :-)

**Comment by progga** [comment]
On Wed, Aug 29, 2018 at 11:32 AM Daniele Scasciafratte
<notifications@github.com> wrote:
>
> I executed with -vvv with no output a part what I written.

Sorry, I missed that.  I have one last suggestion.  You mentioned
earlier you are running Footle inside a VM (which is fine) and you
have also *previously* configured Xdebug to work with other tools.  If
those tools are outside the VM, then Xdebug will *not* try to talk to
Footle as Footle is running *inside* the VM.  So the values of
xdebug.remote_host and/or xdebug.remote_connect_back PHP options are
worth checking.

**Comment by Mte90** [comment]
Yes I was thinking the same and tried with `-codebase-remote` but didn't worked, showed only the files of footle and not the path I written.

**Comment by progga** [comment]
On Wed, Aug 29, 2018 at 1:36 PM Daniele Scasciafratte
<notifications@github.com> wrote:
>
> Yes I was thinking the same and tried with -codebase-remote but didn't worked, showed only the files of footle and not the path I written.

*-codebase-remote* will only work if you *also* provide the
*-codebase* option.  Here is an example: $ footle -codebase
/path/of/php/code/in/local/machine/ -codebase-remote
/path/of/php/code/in/vm/

Alternatively, launch footle from inside your *local copy* of the PHP
code.  Example:
$ cd /path/of/php/code/in/your/local/machine/
$ /path/of/footle -codebase-remote /path/of/php/code/in/vm/

Please note that when using VMs, the easiest way to configure Footle
will be to just run it inside the VM.  This will, of course, involve
*not* turning on xdebug.remote_connect_back *or* not touching
xdebug.remote_host.

**Comment by Mte90** [comment]
Ok I didn't know that I have to use both the parameters (I got no errors).
I have to try changing that parameter and see how works.

My personal opinion is to add more alerts somewhere to help on getting working.

**Comment by progga** [comment]
On Wed, Aug 29, 2018 at 6:06 PM Daniele Scasciafratte
<notifications@github.com> wrote:
>
> My personal opinion is to add more alerts somewhere to help on getting working.

I agree.  I have noted it down.
